version: "3"

services:
  verged:
    build:
      context: .
      dockerfile: Dockerfile.verged
    restart: always
    volumes:
      - ./verge:/root/.verge
    networks:
      - host
  eps:
    build:
      context: .
      dockerfile: Dockerfile.eps
    ports:
      - 127.0.0.1:50002:50002
    restart: unless-stopped
    volumes:
      - ./verge:/root/.verge
    networks:
      - host
    links:
      - verged
networks:
  host:
